version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  nestjs-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/characters
    volumes:
      - .:/app
    command: npm run start:dev
volumes:
  mongo-data: